import { TransactionFormView } from '@/packages/pilgrim/transaction/presentation/view/form';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Ajukan & Registrasi Visa Umrah Digital | Badalin Portal',
  description:
    'Langkah mudah registrasi visa Umrah secara digital. Badalin menyediakan form pengajuan cerdas dengan teknologi OCR Paspor otomatis, manajemen jamaah grup, dan pemesanan akomodasi Umrah DIY yang aman.',
  metadataBase: new URL('https://badalin.visa.com'),
  alternates: {
    canonical: '/transactions/form',
  },
  openGraph: {
    title: 'Ajukan & Registrasi Visa Umrah Digital | Badalin Digital Wizard',
    description:
      'Form pengajuan visa Umrah Mandiri yang ringkas dan aman. Input data jamaah dengan OCR Paspor, kelola manifest grup, dan atur detail logistik perjalanan ibadah Anda dalam satu platform.',
    url: 'https://badalin.visa.com/transactions/form',
    siteName: 'Badalin - Portal Umrah Mandiri Digital',
    images: [
      {
        url: '/og-image.webp',
        width: 1200,
        height: 630,
        alt: 'Badalin Form - Ajukan Visa Umrah dengan OCR Paspor',
      },
    ],
    locale: 'id_ID',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Registrasi Visa Umrah Tanpa Ribet | Badalin Digital',
    description:
      'Solusi cerdas Umrah Mandiri. Isi form pengajuan visa dengan teknologi terbaru yang cepat dan akurat untuk jamaah Indonesia.',
    images: ['/og-image.webp'],
  },
  authors: [
    {
      name: 'Brilian Rachmad Nurwachidin',
      url: 'https://brilianrachmad.vercel.app',
    },
  ],
  publisher: 'Badalin',
  keywords: [
    // Brand
    'Badalin',
    'Badalin Visa',
    'Badalin Umrah',

    // Page Specific
    'Ajukan Visa Umrah',
    'Form Pengajuan Visa',
    'OCR Paspor Otomatis',
    'Input Data Jamaah Umrah',
    'Registrasi Visa Online',
    'Umrah DIY',
    'Booking Visa Digital',

    // Core Services
    'Portal Visa Jamaah',
    'Portal Umrah Mandiri',
    'Tracker Visa Digital',
    'Visa Umrah Online',
    'Cek Status Visa Umrah',
    'Update Visa Umrah Real-time',
    'Sistem Tracker Visa No.1',
    'Platform manajemen visa dan jamaah mandiri paling transparan dan aman',

    // Features
    'OCR Paspor Umrah',
    'Scan Paspor Digital',
    'Manajemen Jamaah Digital',
    'Manifest Umrah Otomatis',
    'Digitalisasi Dokumen Umrah',

    // Locations
    'Jakarta',
    'Jakarta Pusat',
    'Jakarta Selatan',
    'Jakarta Barat',
    'Jakarta Timur',
    'Jakarta Utara',
    'Surabaya',
    'Sidoarjo',
    'Gresik',
    'Malang',
    'Batu',
    'Pasuruan',
    'Probolinggo',
    'Jember',
    'Banyuwangi',
    'Madiun',
    'Kediri',
    'Blitar',
    'Mojokerto',
    'Jombang',
    'Tuban',
    'Lamongan',
    'Bojonegoro',
    'Bandung',
    'Bekasi',
    'Depok',
    'Tangerang',
    'Tangerang Selatan',
    'Bogor',
    'Cimahi',
    'Tasikmalaya',
    'Cirebon',
    'Semarang',
    'Solo',
    'Surakarta',
    'Yogyakarta',
    'Sleman',
    'Bantul',
    'Magelang',
    'Pekalongan',
    'Tegal',
    'Medan',
    'Deli Serdang',
    'Binjai',
    'Pematangsiantar',
    'Banda Aceh',
    'Lhokseumawe',
    'Palembang',
    'Pekanbaru',
    'Batam',
    'Tanjung Pinang',
    'Padang',
    'Bukittinggi',
    'Jambi',
    'Bengkulu',
    'Bandar Lampung',
    'Metro',
    'Pangkal Pinang',
    'Denpasar Bali',
    'Badung',
    'Mataram',
    'Lombok',
    'Kupang',
    'Makassar',
    'Maros',
    'Gowa',
    'Manado',
    'Kendari',
    'Palu',
    'Gorontalo',
    'Mamuju',
    'Banjarmasin',
    'Banjarbaru',
    'Balikpapan',
    'Samarinda',
    'Pontianak',
    'Palangkaraya',
    'Tarakan',
    'IKN Nusantara',
    'Ambon',
    'Ternate',
    'Jayapura',
    'Sorong',
    'Manokwari',
    'Merauke',

    // Performance/Quality
    'Harga Termurah',
    'Pelayanan Terbaik',
    'Transparan',
    'Aman',
    'Sistem Profesional',
    'Teknologi Terbaru',
  ],
  robots: {
    index: false,
    follow: true,
    nocache: true,
  },
  other: {
    'article:author': 'Brilian Rachmad Nurwachidin',
    'article:publisher': 'Badalin',
    'geo.region': 'ID-JI',
    'geo.placename': 'Sidoarjo, Jawa Timur, Indonesia',
    'geo.position': '-7.4478;112.7183',
    ICBM: '-7.4478, 112.7183',
    'apple-mobile-web-app-capable': 'yes',
    'apple-mobile-web-app-status-bar-style': 'black-translucent',
  },
};

export default TransactionFormView;
