import { ManagementListView } from '@/packages/pilgrim/management/presentation/view/list';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Manajemen Keluarga & Grup Jamaah | Badalin Portal',
  description:
    'Kelola data anggota keluarga dan grup jamaah Umrah Anda secara terpusat. Pantau status kelengkapan manifest, scan paspor via OCR, dan pastikan kesiapan dokumen administrasi ibadah Anda.',
  metadataBase: new URL('https://visa.serbaserbiumroh.id'),
  alternates: {
    canonical: '/family',
  },
  openGraph: {
    title: 'Manajemen Keluarga & Grup Jamaah | Badalin Digital Portal',
    description:
      'Dashboard manajemen jamaah mandiri. Tambah anggota keluarga, lengkapi data manifest dengan OCR Paspor, dan kelola grup jamaah Umrah Anda dalam satu sistem digital yang aman.',
    url: 'https://visa.serbaserbiumroh.id/family',
    siteName: 'Badalin - Portal Umrah Mandiri Digital',
    images: [
      {
        url: '/og-image.webp',
        width: 1200,
        height: 630,
        alt: 'Badalin Family Management - Kelola Grup Keluarga Jamaah',
      },
    ],
    locale: 'id_ID',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Kelola Manifest Keluarga Jamaah | Badalin Digital',
    description:
      'Platform digital untuk manajemen manifest keluarga jamaah Umrah Mandiri. Solusi OCR paspor tercepat dan terakurat untuk dokumentasi ibadah Anda.',
    images: ['/og-image.webp'],
  },
  authors: [
    {
      name: 'Kewebin Indonesia',
      url: 'https://kewebin.id',
    },
  ],
  publisher: 'Badalin',
  keywords: [
    // Brand
    'Badalin',
    'Badalin Visa',
    'Badalin Umrah',

    // Module Specific
    'Manajemen Keluarga Jamaah',
    'Daftar Manifest Keluarga Umrah',
    'Grup Keluarga Badalin',
    'Status Kelengkapan Paspor Jamaah Digital',
    'Manajemen Data Jamaah OCR',
    'Pendaftaran Keluarga Umrah Online',

    // Core Services
    'Portal Visa Jamaah',
    'Portal Umrah Mandiri',
    'Tracker Visa Digital',
    'Effortlessly manage your Umrah',
    'Platform manajemen visa dan jamaah mandiri paling transparan dan aman',

    // Features
    'OCR Paspor Umrah',
    'Scan Paspor Digital',
    'Manifest Umrah Otomatis',
    'Digitalisasi Dokumen Umrah',

    // Locations
    'Jakarta',
    'Jakarta Pusat',
    'Jakarta Selatan',
    'Jakarta Barat',
    'Jakarta Timur',
    'Jakarta Utara',
    'Surabaya',
    'Sidoarjo',
    'Gresik',
    'Malang',
    'Batu',
    'Pasuruan',
    'Probolinggo',
    'Jember',
    'Banyuwangi',
    'Madiun',
    'Kediri',
    'Blitar',
    'Mojokerto',
    'Jombang',
    'Tuban',
    'Lamongan',
    'Bojonegoro',
    'Bandung',
    'Bekasi',
    'Depok',
    'Tangerang',
    'Tangerang Selatan',
    'Bogor',
    'Cimahi',
    'Tasikmalaya',
    'Cirebon',
    'Semarang',
    'Solo',
    'Surakarta',
    'Yogyakarta',
    'Sleman',
    'Bantul',
    'Magelang',
    'Pekalongan',
    'Tegal',
    'Medan',
    'Deli Serdang',
    'Binjai',
    'Pematangsiantar',
    'Banda Aceh',
    'Lhokseumawe',
    'Palembang',
    'Pekanbaru',
    'Batam',
    'Tanjung Pinang',
    'Padang',
    'Bukittinggi',
    'Jambi',
    'Bengkulu',
    'Bandar Lampung',
    'Metro',
    'Pangkal Pinang',
    'Denpasar Bali',
    'Badung',
    'Mataram',
    'Lombok',
    'Kupang',
    'Makassar',
    'Maros',
    'Gowa',
    'Manado',
    'Kendari',
    'Palu',
    'Gorontalo',
    'Mamuju',
    'Banjarmasin',
    'Banjarbaru',
    'Balikpapan',
    'Samarinda',
    'Pontianak',
    'Palangkaraya',
    'Tarakan',
    'IKN Nusantara',
    'Ambon',
    'Ternate',
    'Jayapura',
    'Sorong',
    'Manokwari',
    'Merauke',

    // Performance/Quality
    'Harga Termurah',
    'Pelayanan Terbaik',
    'Transparan',
    'Aman',
    'Sistem Profesional',
  ],
  robots: {
    index: false,
    follow: true,
    nocache: true,
  },
  other: {
    'article:author': 'Kewebin Indonesia',
    'article:publisher': 'Badalin',
    'geo.region': 'ID-JI',
    'geo.placename': 'Sidoarjo, Jawa Timur, Indonesia',
    'geo.position': '-7.4478;112.7183',
    ICBM: '-7.4478, 112.7183',
    'apple-mobile-web-app-capable': 'yes',
    'apple-mobile-web-app-status-bar-style': 'black-translucent',
  },
};

export default function FamilyPage() {
  return <ManagementListView />;
}
