import { SubmissionsMonitoring } from '@/packages/provider/submissions/presentation/view/list';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Monitoring Pengajuan Visa | Portal Partner | Badalin Digital',
  description: 'Pantau status dan kelola daftar pengajuan visa Umrah seluruh jamaah secara real-time melalui dashboard B2B Badalin.',
  metadataBase: new URL('https://visa.serbaserbiumroh.id'),
  openGraph: {
    title: 'Monitoring Pengajuan Visa | Portal Partner',
    description: 'Pantau status dan kelola daftar pengajuan visa Umrah seluruh jamaah secara real-time melalui dashboard B2B Badalin.',
    url: 'https://visa.serbaserbiumroh.id',
    siteName: 'Badalin - B2B Umrah Provider Portal',
    images: [
      {
        url: '/og-image.webp',
        width: 1200,
        height: 630,
        alt: 'Monitoring Pengajuan Visa - Portal Partner',
      },
    ],
    locale: 'id_ID',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Monitoring Pengajuan Visa | Portal Partner',
    description: 'Kelola dan pantau seluruh status pengajuan visa jamaah Umrah.',
    images: ['/og-image.webp'],
  },
  authors: [
    {
      name: 'Kewebin Indonesia',
      url: 'https://kewebin.id',
    },
  ],
  publisher: 'Badalin',
  keywords: [
    // Brand
    'Badalin',
    'Badalin Visa',
    'Badalin Umrah',

    // Page Specific
    'Monitoring Pengajuan Visa',
    'Daftar Pengajuan Visa Umrah',
    'Status Visa Umrah',
    'Manajemen Pengajuan Visa',
    'Dashboard Pengajuan Travel',

    // Locations
    'Jakarta',
    'Jakarta Pusat',
    'Jakarta Selatan',
    'Jakarta Barat',
    'Jakarta Timur',
    'Jakarta Utara',
    'Surabaya',
    'Sidoarjo',
    'Gresik',
    'Malang',
    'Batu',
    'Pasuruan',
    'Probolinggo',
    'Jember',
    'Banyuwangi',
    'Madiun',
    'Kediri',
    'Blitar',
    'Mojokerto',
    'Jombang',
    'Tuban',
    'Lamongan',
    'Bojonegoro',
    'Bandung',
    'Bekasi',
    'Depok',
    'Tangerang',
    'Tangerang Selatan',
    'Bogor',
    'Cimahi',
    'Tasikmalaya',
    'Cirebon',
    'Semarang',
    'Solo',
    'Surakarta',
    'Yogyakarta',
    'Sleman',
    'Bantul',
    'Magelang',
    'Pekalongan',
    'Tegal',
    'Medan',
    'Deli Serdang',
    'Binjai',
    'Pematangsiantar',
    'Banda Aceh',
    'Lhokseumawe',
    'Palembang',
    'Pekanbaru',
    'Batam',
    'Tanjung Pinang',
    'Padang',
    'Bukittinggi',
    'Jambi',
    'Bengkulu',
    'Bandar Lampung',
    'Metro',
    'Pangkal Pinang',
    'Denpasar Bali',
    'Badung',
    'Mataram',
    'Lombok',
    'Kupang',
    'Makassar',
    'Maros',
    'Gowa',
    'Manado',
    'Kendari',
    'Palu',
    'Gorontalo',
    'Mamuju',
    'Banjarmasin',
    'Banjarbaru',
    'Balikpapan',
    'Samarinda',
    'Pontianak',
    'Palangkaraya',
    'Tarakan',
    'IKN Nusantara',
    'Ambon',
    'Ternate',
    'Jayapura',
    'Sorong',
    'Manokwari',
    'Merauke',

    // Performance/Quality
    'Harga Termurah',
    'Pelayanan Terbaik',
    'Transparan',
    'Aman',
  ],
  robots: {
    index: false,
    follow: true,
    nocache: true,
  },
  other: {
    'article:author': 'Kewebin Indonesia',
    'article:publisher': 'Badalin',
    'geo.region': 'ID-JI',
    'geo.placename': 'Sidoarjo, Jawa Timur, Indonesia',
    'geo.position': '-7.4478;112.7183',
    ICBM: '-7.4478, 112.7183',
    'apple-mobile-web-app-capable': 'yes',
    'apple-mobile-web-app-status-bar-style': 'black-translucent',
  },
};

export default SubmissionsMonitoring;
