import { TransactionManagementView } from '@/packages/pilgrim/transaction/presentation/view';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Riwayat Transaksi & Pengajuan Visa Umrah | Badalin Portal',
  description:
    'Pantau dan kelola semua pengajuan visa Umrah Anda secara real-time di Badalin. Platform nomor 1 untuk tracking status visa, riwayat transaksi transparan, dan manajemen manifest jamaah digital.',
  metadataBase: new URL('https://visa.serbaserbiumroh.id'),
  alternates: {
    canonical: '/transactions',
  },
  openGraph: {
    title: 'Riwayat Transaksi & Pengajuan Visa Umrah | Badalin Digital Portal',
    description:
      'Kelola pengajuan visa Umrah Anda dengan sistem tracker real-time. Akses riwayat transaksi, cari data jamaah, dan pantau status dokumen dalam satu dashboard transparan.',
    url: 'https://visa.serbaserbiumroh.id/transactions',
    siteName: 'Badalin - Portal Umrah Mandiri Digital',
    images: [
      {
        url: '/og-image.webp',
        width: 1200,
        height: 630,
        alt: 'Badalin Transactions - Kelola Pengajuan Visa Umrah',
      },
    ],
    locale: 'id_ID',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Kelola Transaksi Visa Umrah Anda | Badalin Tracker',
    description:
      'Sistem tracking visa dan riwayat transaksi Umrah Mandiri paling transparan di Indonesia. Cek status pengajuan Anda sekarang.',
    images: ['/og-image.webp'],
  },
  authors: [
    {
      name: 'Brilian Rachmad Nurwachidin',
      url: 'https://brilianrachmad.vercel.app',
    },
  ],
  publisher: 'Badalin',
  keywords: [
    // Brand
    'Badalin',
    'Badalin Visa',
    'Badalin Umrah',

    // Page Specific
    'Riwayat Transaksi Umrah',
    'Transaksi Visa Online',
    'Kelola Pengajuan Visa',
    'Daftar Transaksi Badalin',
    'Status Visa Real-time',
    'Tracking Visa Umrah Jakarta Surabaya Sidoarjo',

    // Core Services
    'Portal Visa Jamaah',
    'Portal Umrah Mandiri',
    'Tracker Visa Digital',
    'Visa Umrah Online',
    'Cek Status Visa Umrah',
    'Sistem Tracker Visa No.1',
    'Effortlessly manage your Umrah',
    'Platform manajemen visa dan jamaah mandiri paling transparan dan aman',

    // Features
    'OCR Paspor Umrah',
    'Scan Paspor Digital',
    'Manajemen Jamaah Digital',
    'Manifest Umrah Otomatis',

    // Locations
    'Jakarta',
    'Jakarta Pusat',
    'Jakarta Selatan',
    'Jakarta Barat',
    'Jakarta Timur',
    'Jakarta Utara',
    'Surabaya',
    'Sidoarjo',
    'Gresik',
    'Malang',
    'Batu',
    'Pasuruan',
    'Probolinggo',
    'Jember',
    'Banyuwangi',
    'Madiun',
    'Kediri',
    'Blitar',
    'Mojokerto',
    'Jombang',
    'Tuban',
    'Lamongan',
    'Bojonegoro',
    'Bandung',
    'Bekasi',
    'Depok',
    'Tangerang',
    'Tangerang Selatan',
    'Bogor',
    'Cimahi',
    'Tasikmalaya',
    'Cirebon',
    'Semarang',
    'Solo',
    'Surakarta',
    'Yogyakarta',
    'Sleman',
    'Bantul',
    'Magelang',
    'Pekalongan',
    'Tegal',
    'Medan',
    'Deli Serdang',
    'Binjai',
    'Pematangsiantar',
    'Banda Aceh',
    'Lhokseumawe',
    'Palembang',
    'Pekanbaru',
    'Batam',
    'Tanjung Pinang',
    'Padang',
    'Bukittinggi',
    'Jambi',
    'Bengkulu',
    'Bandar Lampung',
    'Metro',
    'Pangkal Pinang',
    'Denpasar Bali',
    'Badung',
    'Mataram',
    'Lombok',
    'Kupang',
    'Makassar',
    'Maros',
    'Gowa',
    'Manado',
    'Kendari',
    'Palu',
    'Gorontalo',
    'Mamuju',
    'Banjarmasin',
    'Banjarbaru',
    'Balikpapan',
    'Samarinda',
    'Pontianak',
    'Palangkaraya',
    'Tarakan',
    'IKN Nusantara',
    'Ambon',
    'Ternate',
    'Jayapura',
    'Sorong',
    'Manokwari',
    'Merauke',

    // Performance/Quality
    'Harga Termurah',
    'Pelayanan Terbaik',
    'Transparan',
    'Aman',
  ],
  robots: {
    index: false,
    follow: true,
    nocache: true,
  },
  other: {
    'article:author': 'Brilian Rachmad Nurwachidin',
    'article:publisher': 'Badalin',
    'geo.region': 'ID-JI',
    'geo.placename': 'Sidoarjo, Jawa Timur, Indonesia',
    'geo.position': '-7.4478;112.7183',
    ICBM: '-7.4478, 112.7183',
    'apple-mobile-web-app-capable': 'yes',
    'apple-mobile-web-app-status-bar-style': 'black-translucent',
  },
};

export default TransactionManagementView;
