import { LoginView } from '@/packages/pilgrim/auth/presentation/view';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title:
    'Badalin | Login Portal Umrah Mandiri & Tracker Visa Digital Terpercaya | Solusi Jamaah Indonesia',
  description:
    'Login ke dashboard Badalin. Platform nomor 1 untuk Umrah Mandiri, Tracker Visa Digital real-time, dan manajemen data jamaah berbasis OCR Paspor. Solusi aman, transparan, dan profesional untuk perjalanan ibadah Anda.',
  metadataBase: new URL('https://visa.serbaserbiumroh.id'),
  alternates: {
    canonical: '/auth/login',
  },
  openGraph: {
    title: 'Badalin | Portal Umrah Mandiri & Tracker Visa Digital No.1 di Indonesia',
    description:
      'Pantau status visa Umrah Anda secara real-time. Kelola manifest jamaah dengan teknologi OCR Paspor. Solusi digital untuk Umrah Mandiri yang lebih mudah dan aman.',
    url: 'https://visa.serbaserbiumroh.id/auth/login',
    siteName: 'Badalin - Portal Umrah Mandiri Digital',
    images: [
      {
        url: '/og-image.webp',
        width: 1200,
        height: 630,
        alt: 'Badalin - Digitalisasi Umrah Mandiri & Tracker Visa Digital',
      },
    ],
    locale: 'id_ID',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Badalin | Portal Umrah Mandiri & Tracker Visa Digital Terpercaya',
    description:
      'Platform Tracker Visa dan Manajemen Jamaah Umrah Mandiri dengan teknologi OCR dan transparansi penuh untuk jamaah Indonesia.',
    images: ['/og-image.webp'],
  },
  authors: [
    {
      name: 'Brilian Rachmad Nurwachidin',
      url: 'https://brilianrachmad.vercel.app',
    },
  ],
  publisher: 'Badalin',
  keywords: [
    // Brand
    'Badalin',
    'Badalin Visa',
    'Badalin Umrah',

    // Core Services
    'Portal Visa Jamaah',
    'Portal Umrah Mandiri',
    'Tracker Visa Digital',
    'Visa Umrah Online',
    'Cek Status Visa Umrah',
    'Update Visa Umrah Real-time',
    'Sistem Tracker Visa No.1',
    'Effortlessly manage your Umrah',
    'Platform manajemen visa dan jamaah mandiri paling transparan dan aman',
    'Effortlessly',

    // Features
    'OCR Paspor Umrah',
    'Scan Paspor Digital',
    'Manajemen Jamaah Digital',
    'Manifest Umrah Otomatis',
    'Digitalisasi Dokumen Umrah',

    // Target Audience / Keywords
    'Jamaah Umrah',
    'Daftar Umrah Mandiri',
    'Umrah DIY',
    'Umrah Backpacker',
    'Umrah Tanpa Travel',
    'Umrah Hemat',
    'Umrah Murah Terpercaya',
    'Haji Mandiri Digital',

    // Locations
    'Jakarta',
    'Jakarta Pusat',
    'Jakarta Selatan',
    'Jakarta Barat',
    'Jakarta Timur',
    'Jakarta Utara',
    'Surabaya',
    'Sidoarjo',
    'Gresik',
    'Malang',
    'Batu',
    'Pasuruan',
    'Probolinggo',
    'Jember',
    'Banyuwangi',
    'Madiun',
    'Kediri',
    'Blitar',
    'Mojokerto',
    'Jombang',
    'Tuban',
    'Lamongan',
    'Bojonegoro',
    'Bandung',
    'Bekasi',
    'Depok',
    'Tangerang',
    'Tangerang Selatan',
    'Bogor',
    'Cimahi',
    'Tasikmalaya',
    'Cirebon',
    'Semarang',
    'Solo',
    'Surakarta',
    'Yogyakarta',
    'Sleman',
    'Bantul',
    'Magelang',
    'Pekalongan',
    'Tegal',
    'Medan',
    'Deli Serdang',
    'Binjai',
    'Pematangsiantar',
    'Banda Aceh',
    'Lhokseumawe',
    'Palembang',
    'Pekanbaru',
    'Batam',
    'Tanjung Pinang',
    'Padang',
    'Bukittinggi',
    'Jambi',
    'Bengkulu',
    'Bandar Lampung',
    'Metro',
    'Pangkal Pinang',
    'Denpasar Bali',
    'Badung',
    'Mataram',
    'Lombok',
    'Kupang',
    'Makassar',
    'Maros',
    'Gowa',
    'Manado',
    'Kendari',
    'Palu',
    'Gorontalo',
    'Mamuju',
    'Banjarmasin',
    'Banjarbaru',
    'Balikpapan',
    'Samarinda',
    'Pontianak',
    'Palangkaraya',
    'Tarakan',
    'IKN Nusantara',
    'Ambon',
    'Ternate',
    'Jayapura',
    'Sorong',
    'Manokwari',
    'Merauke',

    // Performance/Quality
    'Harga Termurah',
    'Pelayanan Terbaik',
    'Transparan',
    'Aman',
    'Sistem Profesional',
    'Teknologi Terbaru',

    // General Search
    'Aplikasi Umrah Terbaik',
    'Platform Ibadah Digital',
    'Dashboard Jamaah Umrah',
  ],
  robots: {
    index: true,
    follow: true,
    nocache: true,
  },
  other: {
    'article:author': 'Brilian Rachmad Nurwachidin',
    'article:publisher': 'Badalin',
    'geo.region': 'ID-JI',
    'geo.placename': 'Sidoarjo, Jawa Timur, Indonesia',
    'geo.position': '-7.4478;112.7183',
    ICBM: '-7.4478, 112.7183',
  },
};

export default LoginView;
