import { SubmissionManifest } from '@/packages/provider/submissions/presentation/view/manifest';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Detail Manifest Jamaah | Portal Partner | Badalin Digital',
  description: 'Lihat dan kelola detail manifest jamaah secara real-time. Pantau dokumen persyaratan, status logistik, serta persiapan keberangkatan jamaah Umrah Anda.',
  metadataBase: new URL('https://visa.serbaserbiumroh.id'),
  openGraph: {
    title: 'Detail Manifest Jamaah | Portal Partner',
    description: 'Lihat dan kelola detail manifest jamaah secara real-time. Pantau dokumen persyaratan, status logistik, serta persiapan keberangkatan jamaah Umrah Anda.',
    url: 'https://visa.serbaserbiumroh.id',
    siteName: 'Badalin - B2B Umrah Provider Portal',
    images: [
      {
        url: '/og-image.webp',
        width: 1200,
        height: 630,
        alt: 'Detail Manifest Jamaah - Portal Partner',
      },
    ],
    locale: 'id_ID',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Detail Manifest Jamaah | Portal Partner',
    description: 'Pantau kelengkapan dokumen dan rincian manifest jamaah Umrah Anda.',
    images: ['/og-image.webp'],
  },
  authors: [
    {
      name: 'Kewebin Indonesia',
      url: 'https://kewebin.id',
    },
  ],
  publisher: 'Badalin',
  keywords: [
    // Brand
    'Badalin',
    'Badalin Visa',
    'Badalin Umrah',

    // Page Specific
    'Detail Manifest Jamaah',
    'Kelengkapan Dokumen Umrah',
    'Persiapan Keberangkatan Umrah',
    'Logistik Jamaah Umrah',
    'Data Jamaah Travel',

    // Locations
    'Jakarta',
    'Jakarta Pusat',
    'Jakarta Selatan',
    'Jakarta Barat',
    'Jakarta Timur',
    'Jakarta Utara',
    'Surabaya',
    'Sidoarjo',
    'Gresik',
    'Malang',
    'Batu',
    'Pasuruan',
    'Probolinggo',
    'Jember',
    'Banyuwangi',
    'Madiun',
    'Kediri',
    'Blitar',
    'Mojokerto',
    'Jombang',
    'Tuban',
    'Lamongan',
    'Bojonegoro',
    'Bandung',
    'Bekasi',
    'Depok',
    'Tangerang',
    'Tangerang Selatan',
    'Bogor',
    'Cimahi',
    'Tasikmalaya',
    'Cirebon',
    'Semarang',
    'Solo',
    'Surakarta',
    'Yogyakarta',
    'Sleman',
    'Bantul',
    'Magelang',
    'Pekalongan',
    'Tegal',
    'Medan',
    'Deli Serdang',
    'Binjai',
    'Pematangsiantar',
    'Banda Aceh',
    'Lhokseumawe',
    'Palembang',
    'Pekanbaru',
    'Batam',
    'Tanjung Pinang',
    'Padang',
    'Bukittinggi',
    'Jambi',
    'Bengkulu',
    'Bandar Lampung',
    'Metro',
    'Pangkal Pinang',
    'Denpasar Bali',
    'Badung',
    'Mataram',
    'Lombok',
    'Kupang',
    'Makassar',
    'Maros',
    'Gowa',
    'Manado',
    'Kendari',
    'Palu',
    'Gorontalo',
    'Mamuju',
    'Banjarmasin',
    'Banjarbaru',
    'Balikpapan',
    'Samarinda',
    'Pontianak',
    'Palangkaraya',
    'Tarakan',
    'IKN Nusantara',
    'Ambon',
    'Ternate',
    'Jayapura',
    'Sorong',
    'Manokwari',
    'Merauke',

    // Performance/Quality
    'Harga Termurah',
    'Pelayanan Terbaik',
    'Transparan',
    'Aman',
  ],
  robots: {
    index: false,
    follow: true,
    nocache: true,
  },
  other: {
    'article:author': 'Kewebin Indonesia',
    'article:publisher': 'Badalin',
    'geo.region': 'ID-JI',
    'geo.placename': 'Sidoarjo, Jawa Timur, Indonesia',
    'geo.position': '-7.4478;112.7183',
    ICBM: '-7.4478, 112.7183',
    'apple-mobile-web-app-capable': 'yes',
    'apple-mobile-web-app-status-bar-style': 'black-translucent',
  },
};

export default function SubmissionManifestPage() {
  return <SubmissionManifest />;
}
