import { TransactionDetailView } from '@/packages/pilgrim/transaction/presentation/view';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Detail Pengajuan & Logistik Visa Umrah | Badalin Portal',
  description:
    'Lihat rincian lengkap pengajuan visa Umrah Anda. Pantau status logistik, rincian pembayaran, voucher hotel Makkah Madinah, serta jadwal penerbangan dalam detail transaksi yang transparan.',
  metadataBase: new URL('https://badalin.visa.com'),
  openGraph: {
    title: 'Detail Pengajuan & Logistik Visa Umrah | Badalin Digital',
    description:
      'Informasi lengkap manifest jamaah, detail logistik, dan status pembayaran visa Umrah. Pantau voucher hotel dan tiket pesawat Anda secara digital dan aman.',
    url: 'https://badalin.visa.com/transactions',
    siteName: 'Badalin - Portal Umrah Mandiri Digital',
    images: [
      {
        url: '/og-image.webp',
        width: 1200,
        height: 630,
        alt: 'Badalin Detail - Status Logistik & Pembayaran Visa Umrah',
      },
    ],
    locale: 'id_ID',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Detail Logistik & Voucher Visa Umrah | Badalin',
    description:
      'Rincian lengkap pengajuan visa Anda. Cek status pembayaran dan rincian transportasi Umrah Mandiri Anda dengan mudah.',
    images: ['/og-image.webp'],
  },
  authors: [
    {
      name: 'Brilian Rachmad Nurwachidin',
      url: 'https://brilianrachmad.vercel.app',
    },
  ],
  publisher: 'Badalin',
  keywords: [
    // Brand
    'Badalin',
    'Badalin Visa',
    'Badalin Umrah',

    // Page Specific
    'Detail Logistik Visa',
    'Status Pembayaran Visa Umrah',
    'Manifest Jamaah Digital',
    'Voucher Hotel Makkah Madinah',
    'Tiket Pesawat Umrah',
    'Bukti Pembayaran Visa',
    'Detail Transaksi Badalin',

    // Locations
    'Jakarta',
    'Jakarta Pusat',
    'Jakarta Selatan',
    'Jakarta Barat',
    'Jakarta Timur',
    'Jakarta Utara',
    'Surabaya',
    'Sidoarjo',
    'Gresik',
    'Malang',
    'Batu',
    'Pasuruan',
    'Probolinggo',
    'Jember',
    'Banyuwangi',
    'Madiun',
    'Kediri',
    'Blitar',
    'Mojokerto',
    'Jombang',
    'Tuban',
    'Lamongan',
    'Bojonegoro',
    'Bandung',
    'Bekasi',
    'Depok',
    'Tangerang',
    'Tangerang Selatan',
    'Bogor',
    'Cimahi',
    'Tasikmalaya',
    'Cirebon',
    'Semarang',
    'Solo',
    'Surakarta',
    'Yogyakarta',
    'Sleman',
    'Bantul',
    'Magelang',
    'Pekalongan',
    'Tegal',
    'Medan',
    'Deli Serdang',
    'Binjai',
    'Pematangsiantar',
    'Banda Aceh',
    'Lhokseumawe',
    'Palembang',
    'Pekanbaru',
    'Batam',
    'Tanjung Pinang',
    'Padang',
    'Bukittinggi',
    'Jambi',
    'Bengkulu',
    'Bandar Lampung',
    'Metro',
    'Pangkal Pinang',
    'Denpasar Bali',
    'Badung',
    'Mataram',
    'Lombok',
    'Kupang',
    'Makassar',
    'Maros',
    'Gowa',
    'Manado',
    'Kendari',
    'Palu',
    'Gorontalo',
    'Mamuju',
    'Banjarmasin',
    'Banjarbaru',
    'Balikpapan',
    'Samarinda',
    'Pontianak',
    'Palangkaraya',
    'Tarakan',
    'IKN Nusantara',
    'Ambon',
    'Ternate',
    'Jayapura',
    'Sorong',
    'Manokwari',
    'Merauke',

    // Performance/Quality
    'Harga Termurah',
    'Pelayanan Terbaik',
    'Transparan',
    'Aman',
  ],
  robots: {
    index: false,
    follow: true,
    nocache: true,
  },
  other: {
    'article:author': 'Brilian Rachmad Nurwachidin',
    'article:publisher': 'Badalin',
    'geo.region': 'ID-JI',
    'geo.placename': 'Sidoarjo, Jawa Timur, Indonesia',
    'geo.position': '-7.4478;112.7183',
    ICBM: '-7.4478, 112.7183',
    'apple-mobile-web-app-capable': 'yes',
    'apple-mobile-web-app-status-bar-style': 'black-translucent',
  },
};

export default TransactionDetailView;
