export enum ESetValue {
  SET_SAMPLE_STATE = 'SET_SAMPLE_STATE',
  SET_NOTIFICATIONS = 'SET_NOTIFICATIONS',
  ADD_NOTIFICATION = 'ADD_NOTIFICATION',
  SET_UNREAD_COUNT = 'SET_UNREAD_COUNT',
  INCREMENT_UNREAD_COUNT = 'INCREMENT_UNREAD_COUNT',
  DECREMENT_UNREAD_COUNT = 'DECREMENT_UNREAD_COUNT',
  MARK_NOTIFICATION_READ = 'MARK_NOTIFICATION_READ',
}
