import { DashboardView } from '@/packages/pilgrim/dashboard/presentation/view';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Dashboard Badalin | Tracking Status Visa Umrah & Riwayat Transaksi Anda',
  description:
    'Kelola pengajuan visa Umrah Anda dengan mudah di dashboard Badalin. Platform nomor 1 untuk Umrah Mandiri, Tracker Visa Digital real-time, dan manajemen data jamaah berbasis OCR Paspor terpercaya.',
  metadataBase: new URL('https://visa.serbaserbiumroh.id'),
  alternates: {
    canonical: '/',
  },
  openGraph: {
    title: 'Dashboard Badalin | Portal Riwayat & Pengajuan Visa Umrah Jamaah',
    description:
      'Akses dashboard Badalin untuk memantau manifest jamaah dan status visa Umrah Anda. Sistem mandiri, transparan, dan profesional dalam satu layar.',
    url: 'https://visa.serbaserbiumroh.id',
    siteName: 'Badalin - Portal Umrah Mandiri Digital',
    images: [
      {
        url: '/og-image.webp',
        width: 1200,
        height: 630,
        alt: 'Badalin Dashboard - Tracking Visa & Riwayat Transaksi',
      },
    ],
    locale: 'id_ID',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Dashboard Badalin | Tracking Status Visa Umrah Real-time',
    description:
      'Pantau semua pengajuan visa Umrah Anda dalam satu dashboard digital. Solusi cerdas untuk Umrah Mandiri Anda.',
    images: ['/og-image.webp'],
  },
  authors: [
    {
      name: 'Brilian Rachmad Nurwachidin',
      url: 'https://brilianrachmad.vercel.app',
    },
  ],
  publisher: 'Badalin',
  keywords: [
    // Brand
    'Badalin',
    'Badalin Visa',
    'Badalin Umrah',

    // Specific to this page
    'Dashboard Badalin',
    'Tracking Visa Umrah',
    'Status Visa Real-time',
    'Riwayat Transaksi Umrah',
    'Ajukan Visa Umrah Mandiri',
    'Portal Jamaah Badalin',
    'Cek Dokumen Umrah',
    'Manifest Jamaah Digital',

    // Core Services
    'Portal Visa Jamaah',
    'Portal Umrah Mandiri',
    'Tracker Visa Digital',
    'Visa Umrah Online',
    'Cek Status Visa Umrah',
    'Update Visa Umrah Real-time',
    'Sistem Tracker Visa No.1',
    'Effortlessly manage your Umrah',
    'Platform manajemen visa dan jamaah mandiri paling transparan dan aman',
    'Effortlessly',

    // Features
    'OCR Paspor Umrah',
    'Scan Paspor Digital',
    'Manajemen Jamaah Digital',
    'Manifest Umrah Otomatis',
    'Digitalisasi Dokumen Umrah',

    // Target Audience / Keywords
    'Jamaah Umrah',
    'Daftar Umrah Mandiri',
    'Umrah DIY',
    'Umrah Backpacker',
    'Umrah Tanpa Travel',
    'Umrah Hemat',
    'Umrah Murah Terpercaya',
    'Haji Mandiri Digital',

    // Locations
    'Jakarta',
    'Jakarta Pusat',
    'Jakarta Selatan',
    'Jakarta Barat',
    'Jakarta Timur',
    'Jakarta Utara',
    'Surabaya',
    'Sidoarjo',
    'Gresik',
    'Malang',
    'Batu',
    'Pasuruan',
    'Probolinggo',
    'Jember',
    'Banyuwangi',
    'Madiun',
    'Kediri',
    'Blitar',
    'Mojokerto',
    'Jombang',
    'Tuban',
    'Lamongan',
    'Bojonegoro',
    'Bandung',
    'Bekasi',
    'Depok',
    'Tangerang',
    'Tangerang Selatan',
    'Bogor',
    'Cimahi',
    'Tasikmalaya',
    'Cirebon',
    'Semarang',
    'Solo',
    'Surakarta',
    'Yogyakarta',
    'Sleman',
    'Bantul',
    'Magelang',
    'Pekalongan',
    'Tegal',
    'Medan',
    'Deli Serdang',
    'Binjai',
    'Pematangsiantar',
    'Banda Aceh',
    'Lhokseumawe',
    'Palembang',
    'Pekanbaru',
    'Batam',
    'Tanjung Pinang',
    'Padang',
    'Bukittinggi',
    'Jambi',
    'Bengkulu',
    'Bandar Lampung',
    'Metro',
    'Pangkal Pinang',
    'Denpasar Bali',
    'Badung',
    'Mataram',
    'Lombok',
    'Kupang',
    'Makassar',
    'Maros',
    'Gowa',
    'Manado',
    'Kendari',
    'Palu',
    'Gorontalo',
    'Mamuju',
    'Banjarmasin',
    'Banjarbaru',
    'Balikpapan',
    'Samarinda',
    'Pontianak',
    'Palangkaraya',
    'Tarakan',
    'IKN Nusantara',
    'Ambon',
    'Ternate',
    'Jayapura',
    'Sorong',
    'Manokwari',
    'Merauke',

    // Performance/Quality
    'Harga Termurah',
    'Pelayanan Terbaik',
    'Transparan',
    'Aman',
    'Sistem Profesional',
    'Teknologi Terbaru',

    // General Search
    'Aplikasi Umrah Terbaik',
    'Platform Ibadah Digital',
    'Dashboard Jamaah Umrah',
  ],
  robots: {
    index: false,
    follow: true,
    nocache: true,
  },
  other: {
    'article:author': 'Brilian Rachmad Nurwachidin',
    'article:publisher': 'Badalin',
    'geo.region': 'ID-JI',
    'geo.placename': 'Sidoarjo, Jawa Timur, Indonesia',
    'geo.position': '-7.4478;112.7183',
    ICBM: '-7.4478, 112.7183',
    'apple-mobile-web-app-capable': 'yes',
    'apple-mobile-web-app-status-bar-style': 'black-translucent',
  },
};

export default DashboardView;
